services:
  configserver:
    image: docker.io/prashant498/configserver:latest
    container_name: configserver_cn
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: "500M"
    networks:
      - bank-network
  discoveryservice:
    image: docker.io/prashant498/bankdiscoveryservice:latest
    container_name: discoveryservice_cn
    ports:
      - "7000:7000"
    deploy:
      resources:
        limits:
          memory: "500M"
    networks:
      - bank-network
  accounts:
    image: docker.io/prashant498/accounts:latest
    container_name: accounts_cn
    ports:
      - "5100:5100"
    deploy:
      resources:
        limits:
          memory: "500M"
    networks:
      - bank-network
  cards:
    image: docker.io/prashant498/cards:latest
    container_name: cards_cn
    ports:
      - "5200:5200"
    deploy:
      resources:
        limits:
          memory: "500M"
    networks:
      - bank-network
  rabbit_cn:
    image: docker.io/rabbitmq:3-management
    container_name: rabbit_cn
    ports:
      - "8080:9000"
    deploy:
      resources:
        limits:
          memory: "500M"
    networks:
      - bank-network
  loans:
    image: docker.io/prashant498/loans:latest
    container_name: loans_cn
    ports:
      - "5300:5300"
    deploy:
      resources:
        limits:
          memory: "500M"
    networks:
      - bank-network


networks:
  bank-network:
    driver: bridge