server:
  port: 6000
spring:
  application:
    name: CONFIG_SERVER
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/prashkmp8/config-repository.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
       probes:
         enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true