server:
  port: 5100

spring:
  application:
    name: ACCOUNT_SERVICE
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  config:
    import: optional:configserver:http://localhost:6000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7000/eureka/