services:
  rabbitmqservice:
    image: docker.io/rabbitmq:3-management
    container_name: rabbit_cn
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    extends:
      file: common-config.yml
      service: network-config-service

  configserver:
    image: docker.io/prashant498/configserver:latest
    container_name: configserver_cn
    ports:
      - "5000:5000"
    depends_on:
      rabbitmqservice:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:5000/actuator/health
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: docker.io/prashant498/accounts:latest
    container_name: accounts_cn
    ports:
      - "5100:5100"
    extends:
      file: common-config.yml
      service: microservice-config

  cards:
    image: docker.io/prashant498/cards:latest
    container_name: cards_cn
    ports:
      - "5200:5200"
    extends:
      file: common-config.yml
      service: microservice-config

  loans:
    image: docker.io/prashant498/loans:latest
    container_name: loans_cn
    ports:
      - "5300:5300"
    extends:
      file: common-config.yml
      service: microservice-config

  discoveryservice:
    extends:
      file: common-config.yml
      service: descovery-service

networks:
  bank-network:
    driver: bridge